export { default as CompromisLogo } from './components/logo/CompromisLogo.vue'
export { default as BCard } from './components/card/BCard.vue'
export { default as BCardList } from './components/card/BCardList.vue'
export { default as BCardSection } from './components/card/BCardSection.vue'
export { default as BButton } from './components/button/BButton.vue'
export { default as BFooter } from './components/logo/BFooter.vue'
