export { default as CompromisLogo } from './components/CompromisLogo.vue'
export { default as BCard } from './components/BCard.vue'
export { default as BCardList } from './components/BCardList.vue'
export { default as BCardSection } from './components/BCardSection.vue'
export { default as BButton } from './components/BButton.vue'
export { default as BFooter } from './components/BFooter.vue'
